<?php

declare(strict_types=1);

$finder = PhpCsFixer\Finder::create()
    ->exclude('bootstrap')
    ->exclude('database/factories')
    ->exclude('resources/assets')
    ->exclude('resources/js')
    ->exclude('resources/sass')
    ->exclude('storage')
    ->exclude('tests')
    ->exclude('vendor')
    ->notPath('app/User.php')
    ->notPath('public/index.php')
    ->notPath('server.php')
    ->ignoreUnreadableDirs()
    ->in(__DIR__);

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setCacheFile(__DIR__ . '/.php_cs.cache')
    ->setRules([
        '@PSR2'                   => true,
        '@PSR12'                  => true,
        '@PSR12:risky'            => true,
        '@PhpCsFixer'             => true,
        '@PhpCsFixer:risky'       => true,
        '@Symfony'                => true,
        'align_multiline_comment' => true,
        'array_syntax'            => ['syntax' => 'short'],
        'binary_operator_spaces'  => [
            'operators' => [
                '=>' => 'align',
                '='  => 'align',
            ],
        ],
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement'  => [
            'statements' => [
                'declare',
                'do',
                'for',
                'foreach',
                'if',
                'switch',
                'try',
            ],
        ],
        'cast_spaces'                            => true,
        'class_attributes_separation'            => true,
        'combine_consecutive_issets'             => true,
        'combine_consecutive_unsets'             => true,
        'compact_nullable_typehint'              => true,
        'concat_space'                           => ['spacing' => 'one'],
        'declare_equal_normalize'                => true,
        'declare_strict_types'                   => true,
        'dir_constant'                           => true,
        'ereg_to_preg'                           => true,
        'escape_implicit_backslashes'            => true,
        'explicit_indirect_variable'             => true,
        'explicit_string_variable'               => true,
        'final_internal_class'                   => true,
        'function_to_constant'                   => true,
        'function_typehint_space'                => true,
        'general_phpdoc_annotation_remove'       => ['annotations' => ['class', 'package', 'author']],
        'general_phpdoc_tag_rename'              => true,
        'heredoc_to_nowdoc'                      => true,
        'include'                                => true,
        'is_null'                                => true,
        'linebreak_after_opening_tag'            => true,
        'list_syntax'                            => [
            'syntax' => 'long',
        ],
        'lowercase_cast'                         => true,
        'magic_constant_casing'                  => true,
        'method_chaining_indentation'            => true,
        'modernize_types_casting'                => true,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'native_function_casing'                 => true,
        'native_function_invocation'             => [
            'exclude' => [
                'count',
                'in_array',
            ],
        ],
        'no_alias_functions'                     => true,
        'no_blank_lines_after_class_opening'     => true,
        'no_blank_lines_after_phpdoc'            => true,
        'no_empty_comment'                       => true,
        'no_empty_phpdoc'                        => true,
        'no_empty_statement'                     => true,
        'no_extra_blank_lines'                   => [
            'tokens' => [
                'break',
                'continue',
                'extra',
                'return',
                'throw',
                'use',
                'parenthesis_brace_block',
                'square_brace_block',
                'curly_brace_block',
            ],
        ],
        'no_homoglyph_names'                          => true,
        'no_leading_import_slash'                     => true,
        'no_leading_namespace_whitespace'             => true,
        'no_mixed_echo_print'                         => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_null_property_initialization'             => true,
        'no_php4_constructor'                         => true,
        'no_short_bool_cast'                          => true,
        'no_singleline_whitespace_before_semicolons'  => true,
        'no_spaces_around_offset'                     => true,
        'no_superfluous_phpdoc_tags'                  => false,
        'no_trailing_comma_in_singleline'             => true,
        'no_unneeded_control_parentheses'             => true,
        'no_unneeded_curly_braces'                    => true,
        'no_unneeded_final_method'                    => true,
        'no_unreachable_default_argument_value'       => true,
        'no_unused_imports'                           => true,
        'no_useless_else'                             => true,
        'no_useless_return'                           => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => true,
        'normalize_index_brace'                       => true,
        'object_operator_without_whitespace'          => true,
        'ordered_class_elements'                      => true,
        'ordered_imports'                             => true,
        'php_unit_construct'                          => true,
        'php_unit_dedicate_assert'                    => true,
        'php_unit_internal_class'                     => false,
        'php_unit_mock'                               => true,
        'php_unit_namespaced'                         => true,
        'php_unit_test_class_requires_covers'         => false,
        'phpdoc_add_missing_param_annotation'         => ['only_untyped' => false],
        'phpdoc_align'                                => ['tags' => ['param']],
        'phpdoc_annotation_without_dot'               => true,
        'phpdoc_indent'                               => true,
        'phpdoc_inline_tag_normalizer'                => true,
        'phpdoc_no_access'                            => true,
        'phpdoc_no_empty_return'                      => true,
        'phpdoc_no_package'                           => true,
        'phpdoc_order'                                => true,
        'phpdoc_return_self_reference'                => true,
        'phpdoc_scalar'                               => true,
        'phpdoc_separation'                           => false,
        'phpdoc_single_line_var_spacing'              => true,
        'phpdoc_summary'                              => true,
        'phpdoc_tag_type'                             => true,
        'phpdoc_to_comment'                           => true,
        'phpdoc_trim'                                 => true,
        'phpdoc_types'                                => true,
        'phpdoc_types_order'                          => [
            'null_adjustment' => 'always_last',
            'sort_algorithm'  => 'alpha',
        ],
        'phpdoc_var_annotation_correct_order'         => true,
        'phpdoc_var_without_name'                     => true,
        'pow_to_exponentiation'                       => true,
        'protected_to_private'                        => true,
        'random_api_migration'                        => true,
        'return_type_declaration'                     => true,
        'self_accessor'                               => true,
        'semicolon_after_instruction'                 => true,
        'short_scalar_cast'                           => true,
        'simple_to_complex_string_variable'           => true,
        'simplified_null_return'                      => true,
        'single_blank_line_before_namespace'          => true,
        'single_line_comment_style'                   => true,
        'single_quote'                                => true,
        'space_after_semicolon'                       => ['remove_in_empty_for_expressions' => true],
        'standardize_not_equals'                      => true,
        'ternary_operator_spaces'                     => true,
        'ternary_to_null_coalescing'                  => true,
        'trailing_comma_in_multiline'                 => ['elements' => ['arrays']],
        'trim_array_spaces'                           => true,
        'unary_operator_spaces'                       => true,
        'void_return'                                 => true,
        'whitespace_after_comma_in_array'             => true,
        'yoda_style'                                  => ['equal' => false, 'identical' => false],
    ])
    ->setFinder($finder);

        // 'ordered_class_elements' => [
        //     'order' => [
        //         'use_trait',
        //         'constant_public',
        //         'constant_protected',
        //         'constant_private',
        //         'property_public',
        //         'property_protected',
        //         'property_private',
        //         'construct',
        //         'destruct',
        //     ],
        // ],
        // 'phpdoc_align' => [
        //     'tags' => [
        //         'param',
        //         'property',
        //         'type',
        //         'var',
        //     ],
        // ],
